cartas = [
  {"name": "A", "value": 1 or 11, "naipe": "PAUS"},
  {"name": "A", "value": 1 or 11, "naipe": "ESPACADAS"},
  {"name": "A", "value": 1 or 11, "naipe": "COPAS"},
  {"name": "A", "value": 1 or 11, "naipe": "OUROS"},
  {"name": "2", "value": 2, "naipe": "PAUS"},
  {"name": "2", "value": 2, "naipe": "ESPACADAS"},
  {"name": "2", "value": 2, "naipe": "COPAS"},
  {"name": "2", "value": 2, "naipe": "OUROS"},
  {"name": "3", "value": 3, "naipe": "PAUS"},
  {"name": "3", "value": 3, "naipe": "ESPACADAS"},
  {"name": "3", "value": 3, "naipe": "COPAS"},
  {"name": "3", "value": 3, "naipe": "OUROS"},
  {"name": "4", "value": 4, "naipe": "PAUS"},
  {"name": "4", "value": 4, "naipe": "ESPACADAS"},
  {"name": "4", "value": 4, "naipe": "COPAS"},
  {"name": "4", "value": 4, "naipe": "OUROS"},
  {"name": "5", "value": 5, "naipe": "PAUS"},
  {"name": "5", "value": 5, "naipe": "ESPACADAS"},
  {"name": "5", "value": 5, "naipe": "COPAS"},
  {"name": "5", "value": 5, "naipe": "OUROS"},
  {"name": "6", "value": 6, "naipe": "PAUS"},
  {"name": "6", "value": 6, "naipe": "ESPACADAS"},
  {"name": "6", "value": 6, "naipe": "COPAS"},
  {"name": "6", "value": 6, "naipe": "OUROS"},
  {"name": "7", "value": 7, "naipe": "PAUS"},
  {"name": "7", "value": 7, "naipe": "ESPACADAS"},
  {"name": "7", "value": 7, "naipe": "COPAS"},
  {"name": "7", "value": 7, "naipe": "OUROS"},
  {"name": "8", "value": 8, "naipe": "PAUS"},
  {"name": "8", "value": 8, "naipe": "ESPACADAS"},
  {"name": "8", "value": 8, "naipe": "COPAS"},
  {"name": "8", "value": 8, "naipe": "OUROS"},
  {"name": "9", "value": 9, "naipe": "PAUS"},
  {"name": "9", "value": 9, "naipe": "ESPACADAS"},
  {"name": "9", "value": 9, "naipe": "COPAS"},
  {"name": "9", "value": 9, "naipe": "OUROS"},
  {"name": "10", "value": 10, "naipe": "PAUS"},
  {"name": "10", "value": 10, "naipe": "ESPACADAS"},
  {"name": "10", "value": 10, "naipe": "COPAS"},
  {"name": "10", "value": 10, "naipe": "OUROS"},
  {"name": "J", "value": 10, "naipe": "PAUS"},
  {"name": "J", "value": 10, "naipe": "ESPACADAS"},
  {"name": "J", "value": 10, "naipe": "COPAS"},
  {"name": "J", "value": 10, "naipe": "OUROS"},
  {"name": "Q", "value": 10, "naipe": "PAUS"},
  {"name": "Q", "value": 10, "naipe": "ESPACADAS"},
  {"name": "Q", "value": 10, "naipe": "COPAS"},
  {"name": "Q", "value": 10, "naipe": "OUROS"},
  {"name": "K", "value": 10, "naipe": "PAUS"},
  {"name": "K", "value": 10, "naipe": "ESPACADAS"},
  {"name": "K", "value": 10, "naipe": "COPAS"},
  {"name": "K", "value": 10, "naipe": "OUROS"}
]